LION/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from registration.backends.simple.views import RegistrationView

# Create a new class that redirects the user to the index page, if successful at logging
class MyRegistrationView(RegistrationView):
    def get_success_url(self,request, user):
        return '/'

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'LION.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('reviews.urls', namespace="reviews")),
    url(r'^admin/', include(admin.site.urls)),

    # overriding the default account pattern
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    (r'^accounts/', include('registration.backends.simple.urls')),
)

reviews/urls.py
from django.conf.urls import patterns, url

from reviews import views

urlpatterns = patterns('',
	# ex: /about
	url(r'^about/$', views.about, name='about'),
	# ex: /contact
	url(r'^contact/$', views.contact, name='contact'),
	url(r'^thanks/$', views.thanks, name='thanks'),
	# ex: /; TODO: eventually, this will be the city landing page
	url(r'^$', views.index, name='index'),
	#ex : /add_restaurant
	url(r'^add_restaurant/$', views.add_restaurant, name='add_restaurant'),
	# ex: /restaurant/1
	url(r'^restaurant/(?P<restaurant_id>\d+)/$', views.restaurant, name='restaurant'),
	# ex: /restaurant/1/addreview
	url(r'^restaurant/(?P<restaurant_id>\d+)/addreview/$', views.add_review, name='addreview'),
	# ex: /restaurant/1/4/vote
	url(r'^restaurant/(?P<restaurant_id>\d+)/(?P<review_id>\d+)/favreview/$', views.fav_review, name='fav_review'),
	# ex: /restaurant/1/vote
	url(r'^restaurant/(?P<restaurant_id>\d+)/favrest/$', views.fav_restaurant, name='fav_restaurant')
)

reviews/models.py
import datetime
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

REVIEW_CHOICES = (
		(True, "Good"),
		(None, "Meh"),		
		(False, "Bad")
	)

class TimeStampedModel(models.Model):
	created = models.DateTimeField(auto_now_add=True, editable=False, default=timezone.now)
	modified = models.DateTimeField(auto_now=True, default=timezone.now)
	created_by = models.ForeignKey(User, default=1)

	class Meta:
		abstract = True

class Restaurant(TimeStampedModel):
	restaurant_name = models.CharField(max_length=200)
	address = models.CharField(max_length=200)
	city = models.CharField(max_length=200)
	state = models.CharField(max_length=2)
	zipcode = models.CharField(max_length=10)
	website = models.CharField(max_length=100, default=None, blank=True)
	phone = models.CharField(max_length=10, blank=True)
	published = models.DateTimeField(null=True, default=None, blank=True)
	upvotes = models.IntegerField(default=0)
	def __str__(self):
		return self.restaurant_name

	def was_published_recently(self):
		return self.published >= timezone.now() - datetime.timedelta(days=1)

	def is_published(self):
		return self.published is not None
	is_published.admin_order_field = 'published'
	is_published.boolean = True
	is_published.short_description = "Published?"

	def formatted_phone_number(self):
		return "%s%s%s-%s%s%s-%s%s%s%s" % tuple(self.phone)

class Review(TimeStampedModel):
	restaurant = models.ForeignKey(Restaurant)
	review_text = models.CharField(max_length=140)
	rating = models.NullBooleanField(choices=REVIEW_CHOICES, default=True)
	upvotes = models.IntegerField(default=0)
	downvotes = models.IntegerField(default=0)
	def __str__(self):
		return self.review_text

class Vote(TimeStampedModel):
	restaurant = models.ForeignKey(Restaurant, default=None)
	review = models.ForeignKey(Review, default=None, null=True)

reviews/forms.py
from django import forms
from reviews.models import Restaurant, Review
from localflavor.us.forms import USStateSelect


class RestaurantForm(forms.ModelForm):
	restaurant_name = forms.CharField(label='Name', widget=forms.TextInput(attrs={'class': 'input-wide', 'placeholder': 'Name'}))
	address = forms.CharField(widget=forms.TextInput(attrs={'class': 'input-wide', 'placeholder': 'Address'}))
	city = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'City'}))
	state = forms.CharField(widget=USStateSelect(), initial="NY")
	zipcode = forms.CharField(label='Zip Code', widget=forms.TextInput(attrs={'type': 'number', 'placeholder': 'Zip Code'}))
	website = forms.URLField(widget=forms.TextInput(attrs={'class': 'input-wide', 'placeholder': 'Website'}), required=False)
	phone = forms.CharField(widget=forms.TextInput(attrs={'type': 'tel', 'placeholder': 'Phone'}))
	class Meta:
		model = Restaurant
		fields = ['restaurant_name', 'address', 'city', 'state', 'zipcode', 'website', 'phone']

class ReviewForm(forms.ModelForm):
	review_text = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control no-resize-text-area', 'rows': 5, 'maxlength': 140, 'placeholder': 'Enter your review here (limit 140 chars)'}))
	class Meta:
		model = Review
		fields = ['review_text', 'rating']

class ContactForm(forms.Form):
    from_email = forms.EmailField(label='Your email', required=True)
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'no-resize-text-area'}))

reviews/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from reviews.forms import RestaurantForm, ReviewForm, ContactForm
from django.core.urlresolvers import reverse
from reviews.models import Restaurant, Review, Vote
from django.http import HttpResponseRedirect
from django.views.decorators.csrf import csrf_protect
from django.core.mail import EmailMessage, BadHeaderError


def about(request):
	return render(request, 'reviews/about.html')

# def contact(request):
# 	return render(request, 'reviews/contact.html')

def thanks(request):
	return render(request, 'reviews/thanks.html')

def index(request):
	restaurant_listing = get_restaurant_listing(request)
	context = { 
	 'restaurant_list': restaurant_listing['restaurant_list'],
	 'user_votes': restaurant_listing['user_votes'],
	 'review_totals' : restaurant_listing['review_totals']
	}
	return render(request, 'reviews/index.html', context)

def get_restaurant_votes(request):
	 if request.user.id == None:
	 	user_votes = None
	 else:
	 	user_votes = Vote.objects.filter(review=None, created_by=request.user).values_list('restaurant__id', flat=True)
	 return user_votes

def get_restaurant_user_votes(request, restaurant):
	if request.user.id == None:
	 	user_votes = None
	else:
		user_votes = Vote.objects.filter(review=None, created_by=request.user).values_list('restaurant__id', flat=True)
	return user_votes

def get_restaurant_listing(request):
	restaurant_list = Restaurant.objects.order_by('restaurant_name')
	user_votes = get_restaurant_votes(request)
	review_totals = {}
	for restaurant in restaurant_list:
		review_count = Review.objects.filter(restaurant=restaurant).count()
		positive_review_count = Review.objects.filter(restaurant=restaurant, rating=True).distinct('created_by').count()
		negative_review_count = Review.objects.filter(restaurant=restaurant, rating=False).distinct('created_by').count()
		mediocre_review_count = Review.objects.filter(restaurant=restaurant, rating=None).distinct('created_by').count()
		review_totals[restaurant.id] = { 'positive_count' : positive_review_count, 'negative_count' : negative_review_count, 'mediocre_count' : mediocre_review_count }

	restaurant_listing = {
		'restaurant_list' : restaurant_list,
		'user_votes' : user_votes,
		'review_totals' : review_totals
	}
	return restaurant_listing
	

def restaurant(request, restaurant_id):
	restaurant = get_object_or_404(Restaurant, pk=restaurant_id)
	all_reviews = get_reviews(request, restaurant)
	return render(request, 'reviews/restaurant.html', 
		{
			'restaurant' : all_reviews['restaurant'],
			'positive_reviews' : all_reviews['positive_reviews'],
			'negative_reviews' : all_reviews['negative_reviews'],
			'mediocre_reviews' : all_reviews['mediocre_reviews'],
			'user_votes' : all_reviews['user_votes']
		})

def get_reviews(request, restaurant):
	positive_reviews = Review.objects.filter(restaurant=restaurant, rating=True).order_by('-upvotes')
	negative_reviews = Review.objects.filter(restaurant=restaurant, rating=False).order_by('-upvotes')
	mediocre_reviews = Review.objects.filter(restaurant=restaurant, rating=None).order_by('-upvotes')
	
	if request.user.id == None:
		user_votes = None
	else:
		user_votes = Vote.objects.filter(restaurant=restaurant, created_by=request.user).values_list('review__id', flat=True)
	all_reviews = {
			'restaurant' : restaurant, 
			'positive_reviews' : positive_reviews,
			'negative_reviews' : negative_reviews,
			'mediocre_reviews' : mediocre_reviews,
			'user_votes' : user_votes
		}
	return all_reviews

def fix_website_url(url):
	correct_url = ""
	if not url:
		return correct_url
	if url.startswith("www"):
		correct_url = "http://" + url
	else:
		correct_url = "http://www." + url
	return correct_url

def add_restaurant(request):
    # A HTTP POST?
    if request.method == 'POST':
        form = RestaurantForm(request.POST)

        # Have we been provided with a valid form?
        if form.is_valid():
            # Save the new restaurant to the database.
            new_restaurant = form.save(commit=False)
            new_restaurant.created_by = request.user
            if not new_restaurant.website.startswith("http"):
            	new_restaurant.website = fix_website_url(new_restaurant.website)
            new_restaurant.save()

            # Now call the index() view.
            # The user will be shown the homepage.
            return HttpResponseRedirect(reverse('reviews:index'))
        else:
            # The supplied form contained errors - just print them to the terminal.
            print form.errors
    else:
        # If the request was not a POST, display the form to enter details.
        form = RestaurantForm()

    # Bad form (or form details), no form supplied...
    # Render the form with error messages (if any).
    return render(request, 'reviews/addrestaurant.html', {'form': form})

def add_review(request, restaurant_id):
	restaurant = get_object_or_404(Restaurant, pk=restaurant_id)
	if request.method == 'POST':
		form = ReviewForm(request.POST)

		if form.is_valid():
			new_review = form.save(commit=False)
			new_review.created_by = request.user
			new_review.restaurant = restaurant
			new_review.save()
			return HttpResponseRedirect(reverse('reviews:restaurant', args=(restaurant_id,)))

		else:
			print form.errors
	else:
		form = ReviewForm()

	return render(request, 'reviews/addreview.html', { 'form': form , 'restaurant': restaurant})

@csrf_protect
def fav_review(request, review_id, restaurant_id):
	review = get_object_or_404(Review, pk=review_id)
	restaurant = get_object_or_404(Restaurant, pk=restaurant_id)
	try:
		vote = Vote.objects.filter(restaurant=restaurant, review=review, created_by=request.user)[:1].get()
	except Vote.DoesNotExist:
			vote = None

	
	if request.method == 'POST':
		if vote == None:
			new_vote = Vote(restaurant=restaurant, review=review)
			new_vote.created_by = request.user
			review.upvotes += 1
			review.save()
			new_vote.save()
		else:
			review.upvotes -= 1
			review.save()
			vote.delete()
		all_reviews = get_reviews(request, restaurant)
		user_votes = all_reviews['user_votes']
		return render(request, 'reviews/review_vote_item.html', {
			'user_votes' : user_votes,
			'review' : review,
			'restaurant' : restaurant
			})
	else:
		return HttpResponseRedirect(reverse('reviews:restaurant', args=(restaurant_id,)))

@csrf_protect
def fav_restaurant(request, restaurant_id):
	restaurant = get_object_or_404(Restaurant, pk=restaurant_id)
	try:
		vote = Vote.objects.filter(restaurant=restaurant, review=None, created_by=request.user)[:1].get()
	except Vote.DoesNotExist:
		vote = None

	if request.method == 'POST':
		if vote == None:
			new_vote = Vote(restaurant=restaurant, review=None)
			new_vote.created_by = request.user
			restaurant.upvotes += 1
			restaurant.save()
			new_vote.save()
		else:
			restaurant.upvotes -= 1
			restaurant.save()
			vote.delete()
		user_votes = get_restaurant_user_votes(request, restaurant)
		return render(request, 'reviews/restaurant_vote_item.html', {
				'restaurant' : restaurant,
				'user_votes' : user_votes
			})
	else:
		return HttpResponseRedirect(reverse('reviews:index'))

def contact(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = "noshlocal feedback"
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            try:
				msg = EmailMessage(subject,message, to=['info@noshlocal.com'])
				msg.send()
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return render(request, 'reviews/thanks.html')
    return render(request, "reviews/contact.html", {'form': form})

def thanks(request):
    return HttpResponse('Thank you for your feedback.')

reviews/templates/reviews/addrestaurant.html
{% extends "reviews/base.html" %}
{% block title %}Add Restaurant - Noshlocal{% endblock %}

{% block content %}
<div>
    <h1>Add Restaurant</h1>

    <form id="restaurant_form" method="post" action="/add_restaurant/">

        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        <ul>
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            <li><label>{{ field.label}}:</label> {{ field }}</li>
        {% endfor %}
        </ul>

        <input type="submit" name="submit" value="Create Restaurant" class="btn btn-primary"/>
        <a href="{% url 'reviews:index' %}" class="btn btn-default" role="button">Cancel</a>
    </form>
</div>
{% endblock %}

reviews/templates/reviews/addreview.html
{% extends "reviews/base.html" %}
{% block title %}Add Review - {{ restaurant.restaurant_name }} - Noshlocal{% endblock %}

{% block content %}
<div id="review_container">
    <h1>Add review for {{ restaurant.restaurant_name }}</h1>

    <form id="review_form" method="post" action="/restaurant/{{restaurant.id}}/addreview/">

        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        <ul>
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            <li><label>{{ field.label}}:</label> {{ field }}</li>
        {% endfor %}
        </ul>

        <input type="submit" name="submit" value="Create Review" class="btn btn-primary"/>
        <a href="{% url 'reviews:restaurant' restaurant.id %}" class="btn btn-default" role="button">Cancel</a>
    </form>
</div>
{% endblock %}

reviews/templates/reviews/base.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">

  <head>
      {% load bootstrap3 %}
      {% bootstrap_css %}
      {% bootstrap_javascript %}
      {% load staticfiles %}
      <link rel="stylesheet" type="text/css" href="{% static 'reviews/css/reviews.css' %}" />
      <link rel="apple-touch-icon" sizes="72x72" href="{% static 'reviews/img/apple-touch-icon-72x72.png' %}">
      <link rel="apple-touch-icon" sizes="114x114" href="{% static 'reviews/img/apple-touch-icon-114x114.png' %}">
      <link rel="apple-touch-icon" sizes="144x144" href="{% static 'reviews/img/apple-touch-icon-144x144.png' %}">
      <link rel="apple-touch-icon" sizes="180x180" href="{% static 'reviews/img/apple-touch-icon-180x180.png' %}">
      <title>{% block title %}{% endblock %}</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="description" content="Straightforward reviews to help you find a great local restaurant in the NY Capital Region" />
  </head>

  <body>
  	<div class="container-fluid">
  		{% include 'reviews/header.html' %}
      	{% block content %}{% endblock %}
        {% include 'reviews/footer.html' %}
  	</div>
  	
  	<script src="http://listjs.com/no-cdn/list.js"></script>
  	<script type="text/javascript" src="{% static 'reviews/js/jquery.cookie.js' %}"></script>
  	<script type="text/javascript" src="{% static 'reviews/js/reviews.js' %}"></script>
  	<script>
    if (document.location.hostname.search("noshlocal.com") !== -1) {
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-66451068-1', 'auto');
      ga('send', 'pageview');
    }
    </script>
  </body>

</html>

reviews/templates/reviews/contact.html
{% extends "reviews/base.html" %}

{% block title %}Contact - Noshlocal{% endblock %}

{% block content %}
	<div class="copy">
		<p>
			noshlocal.com is currently in public beta. We expect a few bugs may occur, but more importantly,
			this is the perfect time to voice your opinion on what you like or don't like about the site. If you
			have any suggestions/comments/questions/issues, please contact us via the form below.
		</p>
	</div>
	<div>
		<form id="contact-form" method="post">
			{% csrf_token %}
        	{% for hidden in form.hidden_fields %}
            	{{ hidden }}
        	{% endfor %}

        	<ul>
        	{% for field in form.visible_fields %}
            	{{ field.errors }}
            	{{ field.help_text }}
            	<li><label>{{ field.label}}:</label> {{ field }}</li>
        	{% endfor %}
        	</ul>

        	<input type="submit" name="Send" value="Send" class="btn btn-primary"/>
		</form>
	</div>

{% endblock %}

reviews/templates/reviews/footer.html
<div id="footer">
	<div class="container">
			<a href="{% url 'reviews:about' %}">About</a>
			<a href="{% url 'reviews:contact' %}">Contact</a>
		<div class="social">
			<div class="twitter">
				<a href="https://twitter.com/noshlocaldotcom" class="twitter-follow-button" data-show-count="false" data-show-screen-name="false">Follow @noshlocaldotcom</a>
			</div>
			<div class="fb-follow" data-href="https://www.facebook.com/noshlocal" data-layout="button" data-show-faces="false"></div>
		</div>
		</div>
	</div>
	<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.4";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
</div>

reviews/templates/reviews/header.html
<div id="header">
	<div id="logo" class="nav-logo">
		<h1><a href="{% url 'reviews:index' %}" class="nosh-logo">noshlocal</a></h1><span>(beta!)</span>
	</div>
	<div id="login" class="nav-items">
	    {% if user.get_username %}
	    	<span><a href="{% url 'auth_logout' %}?next=/">Logout</a></span>
	    {% else %}
	    	<a href="{% url 'auth_login' %}?next={{ request.path }}">Login</a>
	    {% endif %}
	</div>
	<div>
		<h5>Straightforward reviews to help you find a great local restaurant.</h5>
	</div>
</div>

reviews/templates/reviews/index.html
{% extends "reviews/base.html" %}

{% block title %}NY Capital Region Restaurant Reviews - Noshlocal{% endblock %}

{% block content %}
	{% if user.get_username %}
	<a href="{% url 'reviews:add_restaurant' %}" class="btn btn-primary">Add New Restaurant</a>
	{% endif %}
	
	<div id="restaurants">
		{% if restaurant_list %}
		<input class="search" placeholder="Filter by name or city" />
		<div class="clr"></div>	
		<ul class="list">
		    {% for restaurant in restaurant_list %}
		  	  {% include 'reviews/restaurant_listing_item.html' %}
		    {% endfor %}
		</ul>
		<div class="clr"></div>
		{% else %}
		    <p>No restaurants are available.</p>
		{% endif %}
	</div>

{% endblock %}

reviews/templates/reviews/restaurant.html
{% extends "reviews/base.html" %}

{% block title %}{{ restaurant.restaurant_name }} Reviews - Noshlocal{% endblock %}

{% block content %}
<div id="rest-container">
	<h2>{{ restaurant.restaurant_name }}</h2>
	<p>
		{{ restaurant.address }} {{ restaurant.city }} {{ restaurant.state }}
		<br>{{ restaurant.formatted_phone_number }}<br>
		<a href="{{ restaurant.website }}">{{ restaurant.website }}</a>
	</p>
</div>

<div class="actions">
{% if user.get_username %}
	<a href="{% url 'reviews:addreview' restaurant.id %}" class="btn btn-primary">Add review</a>
{% else %}
	<a href="{% url 'auth_login' %}?next={{ request.path }}">Login to add review</a>
{% endif %}
<a href="{% url 'reviews:index' %}" class="btn btn-default">Back</a>
</div>

{% include 'reviews/reviews.html' %}

{% endblock %}

reviews/templates/reviews/restaurant_list.html
<div id="restaurants">
	{% if restaurant_list %}
	<input class="search" placeholder="Search" />
	<div class="clr"></div>
	<ul class="list">
	    {% for restaurant in restaurant_list %}
	  	  {% include 'reviews/restaurant_listing_item.html' %}
	    {% endfor %}
	</ul>
	{% else %}
	    <p>No restaurants are available.</p>
	{% endif %}
</div>

reviews/templates/reviews/restaurant_listing_item.html
<li>
	<div class="rest-item col-md-3">
		<a href="{% url 'reviews:restaurant' restaurant.id %}" class="rest-name">{{ restaurant.restaurant_name }}</a>
		<div class="rest-city">{{ restaurant.city}}</div>

		{% include 'reviews/restaurant_vote_item.html' %}
		
		<div class="review-totals">
			{% for id, totals in review_totals.iteritems %}
				{% if id == restaurant.id %}
					<span>Reviews: </span>
					<span class="glyphicon glyphicon-thumbs-up">{{totals.positive_count}}</span>
					<span class="glyphicon glyphicon-minus">{{totals.mediocre_count}}</span>
					<span class="glyphicon glyphicon-thumbs-down">{{totals.negative_count}}</span>
				{% endif %}
			{% endfor %}
		</div>
	</div>
	<div class="clr"></div>
</li>

reviews/templates/reviews/restaurant_vote_item.html
<div class="rest-voting">
	<span>Upvotes: {{ restaurant.upvotes }}</span>
	{% if user.get_username %}
	<div class="vote">
		<a href="#" onclick="favoriteRestaurant({{ restaurant.id }}, {{ user_votes }}, this)">
			{% if not restaurant.id in user_votes %}
				<span class="glyphicon glyphicon-star-empty"></span>
			{% else %}
				<span class="glyphicon glyphicon-star"></span>
			{% endif %}
		</a>
	</div>
	{% endif %}
</div>

reviews/templates/reviews/review_vote_item.html
<div class="voting">
	<span>Upvotes: {{ review.upvotes }}</span>
	{% if user.get_username %}
	<div class="vote">
		<a href="#" onclick="favoriteReview({{ review.id }}, {{ restaurant.id }}, this)">
			{% if not review.id in user_votes %}
				<span class="glyphicon glyphicon-star-empty"></span>
			{% else %}
				<span class="glyphicon glyphicon-star"></span>
			{% endif %}
		</a>
	</div>
	{% endif %}
</div>

reviews/templates/reviews/reviews.html
<div class="reviews">

	<div id="positive" class="col-md-4">
		{% if positive_reviews %}
			<ul>
				{% for positive in positive_reviews %}
					<li>
						<div id="{{ positive.id }}">
							{{ positive.review_text }}</br>
							<div class="voting">
								<span>Upvotes: {{ positive.upvotes }}</span>
								{% if user.get_username %}
								<div class="vote">
									<a href="#" onclick="favoriteReview({{ positive.id }}, {{ restaurant.id }}, this)">
										{% if not positive.id in user_votes %}
											<span class="glyphicon glyphicon-star-empty"></span>
										{% else %}
											<span class="glyphicon glyphicon-star"></span>
										{% endif %}
									</a>
								</div>
								{% endif %}
							</div>
							<div class="reviewer">
								<span>Author: {{ positive.created_by}}</span>
							</div>
						</div>
					</li>
				{% endfor %}
			</ul>
		{% endif %}
	</div>
	<div id="mediocre" class="col-md-4">
		{% if mediocre_reviews %}
			<ul>
				{% for mediocre in mediocre_reviews %}
					<li>
						<div>
							{{ mediocre.review_text }}</br>
							<div class="voting">
								<span>Upvotes: {{ mediocre.upvotes }}</span>
								{% if user.get_username %}
								<div class="vote">
									<a href="#" onclick="favoriteReview({{ mediocre.id }}, {{ restaurant.id }}, this)">
										{% if not mediocre.id in user_votes %}
											<span class="glyphicon glyphicon-star-empty"></span>
										{% else %}
											<span class="glyphicon glyphicon-star"></span>
										{% endif %}
									</a>
								</div>
								{% endif %}
							</div>
							<div class="reviewer">
								<span>Author: {{ mediocre.created_by}}</span>
							</div>
						</div>
					</li>
				{% endfor %}
			</ul>
		{% endif %}
	</div>
	<div id="negative" class="col-md-4">
		{% if negative_reviews %}
			<ul>
				{% for negative in negative_reviews %}
					<li>
						<div>
							{{ negative.review_text }}</br>
							<div class="voting">
								<span>Upvotes: {{ negative.upvotes }}</span>
								{% if user.get_username %}
								<div class="vote">
									<a href="#" onclick="favoriteReview({{ negative.id }}, {{ restaurant.id }}, this)">
										{% if not negative.id in user_votes %}
											<span class="glyphicon glyphicon-star-empty"></span>
										{% else %}
											<span class="glyphicon glyphicon-star"></span>
										{% endif %}
									</a>
								</div>
								{% endif %}
							</div>
							<div class="reviewer">
								<span>Author: {{ negative.created_by}}</span>
							</div>
						</div>
					</li>
				{% endfor %}
			</ul>
		{% endif %}
	</div>	
	
	{% if not positive_reviews and not negative_reviews and not mediocre_reviews %}
	    <p>This restaurant does not have any reviews yet. Add one!</p>
	{% endif %}

	

</div>

reviews/templates/reviews/thanks.html
{% extends "reviews/base.html" %}

{% block title %}Thanks - Noshlocal{% endblock %}

{% block content %}
	<div class="copy">
		<p>
			Thanks for the feedback!
		</p>
	</div>


{% endblock %}